// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanNoteServer.Data;

#nullable disable

namespace PlanNotesServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlanNoteServer.Models.DailyReflections", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("AfternoonReview")
                        .HasColumnType("TEXT");

                    b.Property<string>("EveningSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("MorningReview")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlanDate")
                        .HasColumnType("DATE");

                    b.Property<decimal?>("TotalScoreAvg")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("PlanDate")
                        .HasDatabaseName("IX_daily_reflections_PlanDate");

                    b.HasIndex("TotalScoreAvg")
                        .HasDatabaseName("IX_daily_reflections_TotalScoreAvg");

                    b.HasIndex("UserID", "PlanDate")
                        .IsUnique()
                        .HasDatabaseName("UQ_daily_reflections_UserID_PlanDate");

                    b.ToTable("daily_reflections", null, t =>
                        {
                            t.HasCheckConstraint("CK_daily_reflections_TotalScoreAvg", "TotalScoreAvg IS NULL OR TotalScoreAvg BETWEEN 0 AND 10");
                        });
                });

            modelBuilder.Entity("PlanNoteServer.Models.DailySchedules", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("TIME");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("PlanDate")
                        .HasColumnType("DATE");

                    b.Property<int?>("SelfScore")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TIME");

                    b.Property<string>("TaskContent")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_daily_schedules_CreatedAt");

                    b.HasIndex("UserID", "PlanDate", "IsCompleted")
                        .HasDatabaseName("IX_daily_schedules_UserID_PlanDate_IsCompleted");

                    b.HasIndex("UserID", "PlanDate", "SortOrder")
                        .HasDatabaseName("IX_daily_schedules_UserID_PlanDate_SortOrder");

                    b.ToTable("daily_schedules", null, t =>
                        {
                            t.HasCheckConstraint("CK_daily_schedules_SelfScore", "SelfScore IS NULL OR SelfScore BETWEEN 1 AND 10");

                            t.HasCheckConstraint("CK_daily_schedules_SortOrder", "SortOrder >= 0");

                            t.HasCheckConstraint("CK_daily_schedules_StartBeforeEnd", "StartTime < EndTime");
                        });
                });

            modelBuilder.Entity("PlanNoteServer.Models.Permissions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PermissionModule")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionCode")
                        .IsUnique();

                    b.HasIndex("PermissionModule");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("PlanNoteServer.Models.RolePermissions", b =>
                {
                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<int>("PermissionID")
                        .HasColumnType("int");

                    b.HasKey("RoleID", "PermissionID");

                    b.HasIndex("PermissionID")
                        .HasDatabaseName("IX_role_permissions_PermissionID");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("PlanNoteServer.Models.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RolesName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RolesName")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("PlanNoteServer.Models.UserCredentials", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("LastLoginIP")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("UserID")
                        .IsUnique()
                        .HasDatabaseName("IX_user_credentials_UserID_Unique");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_user_credentials_Username_Unique");

                    b.ToTable("user_credentials", (string)null);
                });

            modelBuilder.Entity("PlanNoteServer.Models.UserRoles", b =>
                {
                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("UserID", "RoleID");

                    b.HasIndex("RoleID");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("PlanNoteServer.Models.Users", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OpenId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UnionId")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("UserStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OpenId")
                        .IsUnique();

                    b.HasIndex("UnionId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PlanNoteServer.Models.WeeklyPlans", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Review")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("WeekEndDate")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("WeekStartDate")
                        .HasColumnType("DATE");

                    b.Property<long?>("YearlyGoalID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_weekly_plans_CreatedAt");

                    b.HasIndex("YearlyGoalID")
                        .HasDatabaseName("IX_weekly_plans_YearlyGoalID");

                    b.HasIndex("UserID", "WeekEndDate")
                        .HasDatabaseName("IX_weekly_plans_UserID_WeekEndDate");

                    b.HasIndex("UserID", "WeekStartDate")
                        .IsUnique()
                        .HasDatabaseName("UQ_weekly_plans_UserID_WeekStartDate");

                    b.ToTable("weekly_plans", null, t =>
                        {
                            t.HasCheckConstraint("CK_weekly_plans_StartBeforeEnd", "WeekStartDate < WeekEndDate");
                        });
                });

            modelBuilder.Entity("PlanNoteServer.Models.YearlyGoals", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("TargetYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.Property<byte>("YearlyStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.HasKey("ID");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_yearly_goals_CreatedAt");

                    b.HasIndex("TargetYear")
                        .HasDatabaseName("IX_yearly_goals_TargetYear");

                    b.HasIndex("UserID", "TargetYear")
                        .HasDatabaseName("IX_yearly_goals_UserID_TargetYear");

                    b.HasIndex("UserID", "YearlyStatus")
                        .HasDatabaseName("IX_yearly_goals_UserID_YearlyStatus");

                    b.ToTable("yearly_goals", null, t =>
                        {
                            t.HasCheckConstraint("CK_yearly_goals_Progress", "Progress >= 0 AND Progress <= 100");

                            t.HasCheckConstraint("CK_yearly_goals_YearlyStatus", "YearlyStatus IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("PlanNoteServer.Models.DailyReflections", b =>
                {
                    b.HasOne("PlanNoteServer.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_daily_reflections_users_UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlanNoteServer.Models.DailySchedules", b =>
                {
                    b.HasOne("PlanNoteServer.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_daily_schedules_users_UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlanNoteServer.Models.RolePermissions", b =>
                {
                    b.HasOne("PlanNoteServer.Models.Permissions", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_role_permissions_permissions_PermissionID");

                    b.HasOne("PlanNoteServer.Models.Roles", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_role_permissions_roles_RoleID");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PlanNoteServer.Models.UserCredentials", b =>
                {
                    b.HasOne("PlanNoteServer.Models.Users", "User")
                        .WithOne()
                        .HasForeignKey("PlanNoteServer.Models.UserCredentials", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_user_credentials_users_UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlanNoteServer.Models.UserRoles", b =>
                {
                    b.HasOne("PlanNoteServer.Models.Roles", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_user_roles_roles_RoleID");

                    b.HasOne("PlanNoteServer.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_user_roles_users_UserID");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlanNoteServer.Models.WeeklyPlans", b =>
                {
                    b.HasOne("PlanNoteServer.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_weekly_plans_users_UserID");

                    b.HasOne("PlanNoteServer.Models.YearlyGoals", "YearlyGoal")
                        .WithMany()
                        .HasForeignKey("YearlyGoalID")
                        .HasConstraintName("FK_weekly_plans_yearly_goals_YearlyGoalID");

                    b.Navigation("User");

                    b.Navigation("YearlyGoal");
                });

            modelBuilder.Entity("PlanNoteServer.Models.YearlyGoals", b =>
                {
                    b.HasOne("PlanNoteServer.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_yearly_goals_users_UserID");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
